[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/hello_world.rs"
name = "Hola Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
